### ISSUE TITLE
Messages.getMessage unknown API response

### ISSUE THREAD

**Issue by rk125** [CumberlandGroup/node-red-contrib-spark#2]
Hello Nicholas!
I'm getting "msg : string [27] error: unknown API response" error when trying to get message using api node with Messages.getMessage. Sending works fine.
Webhook is attaching to Spark, and after posting message into room, I get ID via parser (following example you have in readme). When passing it to api node, it gives error. I can see message using ID in https://developer.ciscospark.com/endpoint-messages-messageId-get.html just fine using that specific ID.
Am I doing something wrong?
Using version 2.0.2
Thanks for great tool!
Reggie

**Comment by nmarus** [comment]
My apologies for the delay in responding.

Just tested a few moments ago. All looks well for valid messageIds that I have tested with. You may wish to insert a debug after the webhook then another after the parser to see what the data payload looks like. Before hitting the messages.getMessage node, the msg.payload should have the following json contents:

``` json
{ "messageId": "somemessageidstring" }
```
