### ISSUE TITLE
Unable to add the node on Bluemix Node-red

### ISSUE THREAD

**Issue by ghost** [CumberlandGroup/node-red-contrib-spark#3]
Hi, I wanna use the node you made. However, when I add the node on Bluemix Node-red, an error occurs. After that, I can't open my Node-red. It depends on which node you added. For example, I could add "node-red-contrib-slack" with no errors. If possible, please give me a solution.

**Comment by nmarus** [comment]
I have not tested this on Bluemix yet. Let me give it a shot and see what's happening. Thanks for the note.

**Comment by ghost** [comment]
Thanks for your quick reply!! I have attached the gif file.  You will see, you could add the node successfully, but then you couldn't open Node-red. The update lasts forever and you can't see the left pane which contains the nodes...
![node-red](https://cloud.githubusercontent.com/assets/19503198/23146264/895ab1d0-f818-11e6-9cbf-81b74f985949.gif)

**Comment by nmarus** [comment]
Give version 2.0.5 a shot. This may fix the problem. I have yet to test on Bluemix.

**Comment by nmarus** [comment]
Just spun up a bluemix instance. Everything is working for me on v2.0.5.
