### ISSUE TITLE
crash after reimport spark nodes

### ISSUE THREAD

**Issue by ionmihalache** [CumberlandGroup/node-red-contrib-spark#4]
Hi,

the nodered crash after reimport sript with spark nodes and the message is:

Can't read from server.  It may not have the appropriate access-control-origin settings.

Regards,

**Comment by nmarus** [comment]
Try v2.0.5. You may have to remove the previous flows and recreate. Also be sure your settings.js file is not setting httpNodeRoot to false.

**Comment by ionmihalache** [comment]
I don't have the issue anymore, I upgraded to v2.0.5 and recreated the nodes
Thank you
